### PR TITLE
General Fixes

### PR DESCRIPTION
**Pull request by simonkurtz-MSFT**
- Fixes most, if not all Markdown linting violations
- Opens all external links in new tab
- Fixes minor grammatical issues

Once this is merged, we will have a very consistent baseline for Markdown. Please install the MarkdownLint extension for VSCode or any other editor you use to stay consistent. Thank you!

### CODE REVIEW

**Review by waelkdouh — APPROVED** [review]
LGTM

**Review by pankajagrawal16 — APPROVED** [review]
Overall looks good to me. Pls make sure none of the mkdocs related conventions break coz of formatting. I did try to check some of those comparing preview deployment with main.. and seems alrite. 

Thanks for contributing.

**Comment by simonkurtz-MSFT** [comment]
@pankajagrawal16, the changes break out the tabbed view into multiple items. If we are particular about the tabbed view, I can adjust the rule to not trigger on that.

image

**Comment by simonkurtz-MSFT** [comment]
#sign-off

**Pull request merged**
